# Generated by Django 3.2.11 on 2022-01-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('imageUrl', models.URLField()),
                ('newsSite', models.CharField(max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('summary', models.CharField(max_length=300)),
                ('publishedAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('events', models.ManyToManyField(blank=True, to='api.Event')),
                ('launches', models.ManyToManyField(blank=True, to='api.Launch')),
            ],
        ),
    ]
