# Generated by Django 3.2.11 on 2022-01-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='launch',
            name='id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
