# Generated by Django 3.2.11 on 2022-02-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imageUrl',
            field=models.URLField(max_length=600),
        ),
    ]
